import { Link } from 'expo-router';
import Head from 'expo-router/head';
import { useMemo, useRef, useState, type ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, ArrowUpRight, Bell, CalendarDays, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, Disc3, Download, Heart, Link2, ListMusic, MapPin, MessageSquare, Pause, Pencil, Play, Plus, Search, Send, Settings, Share2, Shuffle, SlidersHorizontal, Trash2, UserRound, UsersRound, X } from 'lucide-react-native';
import { SearchField } from '@volna/messaging-client/search-field';
import { ScreenTopBar, ScreenTopBarEnvironment } from '@volna/messaging-client/screen-top-bar';
import { AppSheetModal } from '@volna/messaging-client/app-sheet';
import { appSheetDesign } from '@volna/messaging-client/sheet-design';
import { LoadingIndicator } from '@volna/messaging-client/loading';
import { MotionDisclosure, useReducedMotion } from '@volna/messaging-client/ui-motion';
import { Avatar as ChatAvatar, DeletionSheet, MessageRow, MessagesEmptyState } from '@volna/messaging-client/react-native-messages';
import { messagingSurfaceErrorMessage, type MessagingMessage } from '@volna/messaging-client/messaging-surface-controller';
import { AppImage } from '../components/AppImage';
import { AnimatedSegmentedControl } from '../components/AnimatedSegmentedControl';
import { AvatarEditButton } from '../components/AvatarEditButton';
import { CalendarPickerModal } from '../components/CalendarPickerModal';
import { CatalogCategoryTile } from '../components/CatalogCategoryTile';
import { CatalogInnerHeader } from '../components/CatalogInnerHeader';
import { CatalogBackDemo } from './CatalogBackDemo';
import { DownloadedMusicHeader } from '../components/DownloadedMusicHeader';
import { CatalogTabs } from '../components/CatalogTabs';
import { ContentTabIndicator } from '../components/ContentTabIndicator';
import { ConnectProfileInterests } from '../components/ConnectProfileInterests';
import { ConnectLikeIcon } from '../components/ConnectLikeIcon';
import { PrimaryTrackPreviewCard } from '../components/PrimaryTrackPreviewCard';
import { EditorAutosaveStatus } from '../components/EditorAutosaveStatus';
import { ExternalReleaseEditorField } from '../components/ExternalReleaseEditorField';
import { PasswordStrengthIndicator } from '../components/PasswordStrengthIndicator';
import { PlaylistGrid } from '../components/PlaylistGrid';
import { MusicCategoryTile, musicCategoryStyles } from '../components/MusicCategoryTile';
import { playlistCategoryArtwork, resolvePlaylistArtwork } from '../music/playlistArtwork';
import { ReleaseMetadataRows } from '../components/ReleaseMetadataRows';
import { SelectionPickerModal } from '../components/SelectionPickerModal';
import { SideMenu } from '../components/SideMenu';
import { TopToast } from '../components/TopToast';
import { VerifiedName } from '../components/VerifiedBadge';
import { VolnaSwitch } from '../components/VolnaSwitch';
import { BottomNavigation } from '../components/navigation';
import { ConnectInterestSelector, ConnectPhotosEditor, MusicGenreSelector } from '../screens/ProfileScreens';
import { ConnectAgeRangeSlider } from '../screens/CommunityScreens';
import { styles as shared } from '../styles';
import type { AppTab, ConnectPhoto, Profile, ToastMessage } from '../types';

// All interactions below are local examples. No session, controller, remote query or
// playback engine is created by this page; examples never edit application data.
import { Action, Stack, Label, Row, noop, covers, genres, demoProfile, type DemoProps, type Specimen } from './demo-shared';
import { productSpecimens } from './product-specimens';
import coverage from './coverage.json';
import fidelity from './fidelity.json';
const specimenKindLabels = { component: 'Компонент приложения', composition: 'Композиция общих стилей', fragment: 'Фрагмент экрана' };

function FoundationDemo() {
  const colors = [['Текст', shared.primaryTrackSearchInput.color], ['Поверхность', appSheetDesign.surfaceColor], ['Нейтральный фон', shared.primaryTrackInputHint.backgroundColor], ['Контур', shared.primaryTrackSearchInputRow.borderColor], ['Подпись', shared.primaryTrackInputHint.color], ['Ошибка', shared.primaryTrackExternalError.color]];
  return <View style={ui.swatches}>{colors.map(([name, color]) => <View key={name} style={ui.swatch}><View style={[ui.swatchPaint, { backgroundColor: color }]} /><Text style={ui.label}>{name}</Text><Text selectable style={ui.caption}>{color}</Text></View>)}</View>;
}
function TypographyDemo() { return <Stack><View style={[ui.neutral, { backgroundColor: '#111' }]}><Text style={shared.connectProfileName}>Заголовок профиля</Text></View><Text style={ui.heading}>Главный заголовок</Text><Text style={shared.primaryTrackSearchTitle}>Название экрана · 16 px</Text><Text style={shared.primaryAuthTextLogin}>Основной текст интерфейса</Text><Text style={shared.bandcampReleaseMeta}>Дата, автор и другие подписи</Text><Text style={shared.primaryTrackExternalError}>Не удалось сохранить. Попробуйте снова.</Text></Stack>; }
function GeometryDemo() { return <Stack><Label>Скругления</Label><Row>{[8, 12, 22, 25].map(radius => <View key={radius} style={[ui.geometry, { borderRadius: radius }]}><Text style={ui.label}>{radius}</Text></View>)}</Row><Label>Интервалы</Label><Row>{[4, 8, 12, 16, 18, 24, 32].map(value => <View key={value} style={ui.spacingItem}><View style={{ width: value, height: 24, backgroundColor: '#d7dee5' }} /><Text style={ui.caption}>{value}</Text></View>)}</Row><Text style={ui.caption}>Кнопки 44–52 px · зона нажатия иконок 44 px · панель до {appSheetDesign.desktopMaxWidth} px</Text></Stack>; }
function IconsDemo() { const icons = { Search, X, Plus, Pencil, Check, CheckCheck, ChevronLeft, ChevronRight, ChevronDown, Bell, MessageSquare, UsersRound, UserRound, CalendarDays, Disc3, ListMusic, MapPin, Heart, Play, Pause, Download, Share2, Send, Shuffle, Settings, SlidersHorizontal, Link2, Trash2 }; return <View style={ui.iconGrid}>{Object.entries(icons).map(([name, Icon]) => <View key={name} style={ui.iconCell}><Icon color="#111" size={23} strokeWidth={1.9} /><Text numberOfLines={1} style={ui.iconName}>{name}</Text></View>)}</View>; }
function ButtonsDemo({ notify }: DemoProps) { return <Stack><Action onPress={() => notify('Основное действие')}>Продолжить</Action><Action secondary onPress={() => notify('Вторичное действие')}>Отмена</Action><Action disabled onPress={noop}>Недоступно</Action><Pressable disabled accessibilityRole="button" accessibilityLabel="Сохраняется" style={[shared.primaryAuthButton, { marginTop: 0 }]}><LoadingIndicator tone="inverse" /></Pressable><Row><Pressable accessibilityRole="button" accessibilityLabel="Добавить" onPress={() => notify('Добавить')} style={[shared.primaryTrackExternalAdd, shared.primaryTrackExternalAddActive]}><Plus color="#111" size={24} /></Pressable><Pressable accessibilityRole="button" onPress={() => notify('Удаление — пример', 'error')}><Text style={shared.primaryTrackExternalError}>Удалить</Text></Pressable></Row></Stack>; }
function SearchDemo() { const [query, setQuery] = useState(''); return <Stack><SearchField placeholder="Поиск музыки" value={query} onChangeText={setQuery} onClear={() => setQuery('')} /><Text style={ui.caption}>Поиск страницы · 44 px · без контура</Text></Stack>; }
function AttachedSearchDemo() { const [query, setQuery] = useState(''); return <View style={shared.primaryTrackInputGroup}><View style={shared.primaryTrackSearchInputRow}><Search color="#6f7b86" size={19} /><TextInput accessibilityLabel="Поиск главного трека — пример" placeholder="Название трека или исполнитель" placeholderTextColor="#8e99a4" value={query} onChangeText={setQuery} style={shared.primaryTrackSearchInput} /></View><Text style={shared.primaryTrackInputHint}>Поиск по каталогу выбранного музыкального сервиса.</Text></View>; }
function LinkDemo({ notify }: DemoProps) { const [value, setValue] = useState(''); const [error, setError] = useState<string | null>(null); return <ExternalReleaseEditorField value={value} onChangeText={next => { setValue(next); setError(null); }} onResolve={() => { setError('Пример ошибки: проверьте ссылку. Введённый текст сохранён.'); notify('Это демонстрация поля, запрос не отправляется'); }} preview={null} isResolving={false} error={error} hint="Поддерживаются ссылки Apple Music, Яндекс Музыки, SoundCloud, Bandcamp и YouTube." />; }
function FormDemo() { const [value, setValue] = useState(''); return <Stack><TextInput accessibilityLabel="Название — пример" placeholder="Название" value={value} onChangeText={setValue} style={[shared.input, { marginTop: 0 }]} /><View style={shared.editAboutField}><Label>О себе</Label><TextInput accessibilityLabel="О себе — пример" multiline placeholder="Расскажите о себе" style={shared.editAboutInput} /></View><Text style={shared.primaryTrackExternalError}>Пример ошибки рядом с полем</Text><Text style={ui.counter}>{value.length}/80</Text></Stack>; }
function PasswordDemo() { const [password, setPassword] = useState(''); return <Stack><TextInput accessibilityLabel="Тестовый пароль — не сохраняется" secureTextEntry autoComplete="off" textContentType="none" value={password} onChangeText={setPassword} placeholder="Тестовый пароль" style={[shared.input, { marginTop: 0 }]} /><PasswordStrengthIndicator password={password} /><Text style={ui.caption}>Используйте вымышленное значение. Поле работает только в этой странице.</Text></Stack>; }
function SegmentsDemo() { const [value, setValue] = useState('all'); const [provider, setProvider] = useState('apple'); return <Stack><AnimatedSegmentedControl accessibilityLabel="Видимость — пример" options={[{ value: 'none', label: 'Никто' }, { value: 'friends', label: 'Друзья' }, { value: 'all', label: 'Все' }]} value={value} onChange={setValue} /><AnimatedSegmentedControl accessibilityLabel="Музыкальный сервис — пример" options={[{ value: 'apple', label: 'Apple Music' }, { value: 'yandex', label: 'Я.Музыка' }]} value={provider} onChange={setProvider} /></Stack>; }
function SwitchDemo() { const [value, setValue] = useState(true); const [checked, setChecked] = useState(false); return <Stack><View style={ui.between}><Label>Уведомления</Label><VolnaSwitch accessibilityLabel="Уведомления — пример" value={value} onValueChange={setValue} /></View><View style={ui.between}><Label>Недоступный переключатель</Label><VolnaSwitch accessibilityLabel="Недоступно — пример" disabled value={false} onValueChange={noop} /></View><Pressable accessibilityRole="checkbox" accessibilityState={{ checked }} aria-checked={checked} onPress={() => setChecked(!checked)} style={ui.row}><View style={[shared.authRulesCheckbox, checked && shared.authRulesCheckboxChecked]}>{checked ? <Check color="#fff" size={16} /> : null}</View><Label>Выбранный пункт</Label></Pressable></Stack>; }
function InterestsDemo() { const [selected, setSelected] = useState(['DJING']); const [music, setMusic] = useState<string[]>([genres[0]]); return <ConnectInterestSelector filterCard selected={selected} onChange={setSelected} musicGenres={music} onChangeMusicGenres={setMusic} />; }
function GenreDemo() { const [selected, setSelected] = useState<string[]>([]); return <MusicGenreSelector filterButton title="Жанры" selected={selected} onChange={setSelected} />; }
function RangeDemo() { const [value, setValue] = useState<[number, number]>([22, 38]); return <Stack><View style={ui.between}><Label>Возраст</Label><Text style={ui.caption}>{value[0]}–{value[1]} лет</Text></View><ConnectAgeRangeSlider maximumAge={60} value={value} onChange={setValue} /></Stack>; }
function PhotosDemo({ notify }: DemoProps) { const [photos, setPhotos] = useState<ConnectPhoto[]>(covers.slice(0, 2).map((url, i) => ({ imageUrl: url, imageKey: `ui-kit-${i}`, thumbnailUrl: url }))); const [about, setAbout] = useState('Музыка, люди и любимые места.'); return <ConnectPhotosEditor photos={photos} about={about} onChangeAbout={setAbout} onChange={setPhotos} onAdd={() => notify('Добавление фотографии — пример')} />; }
function GoalsDemo() { const [active, setActive] = useState(['Коллаборации']); return <View style={shared.connectGoalChips}>{['Без конкретики', 'Коллаборации', 'Знакомства', 'Романтика', 'Набор в команду', 'Волонтёрство'].map(label => <Pressable accessibilityRole="button" accessibilityState={{ selected: active.includes(label) }} key={label} onPress={() => setActive(previous => previous.includes(label) ? previous.filter(x => x !== label) : [...previous, label])} style={[shared.connectGoalChip, active.includes(label) && shared.connectGoalChipActive]}><Text style={[shared.connectGoalChipText, active.includes(label) && shared.connectGoalChipTextActive]}>{label}</Text></Pressable>)}</View>; }
function HeadersDemo({ notify }: DemoProps) { return <Stack><ScreenTopBarEnvironment.Provider value={{ messageCount: 3, notificationCount: 12, onActionFeedback: noop }}><ScreenTopBar title="Музыка" onOpenMessages={() => notify('Сообщения')} onOpenNotifications={() => notify('Уведомления')} onOpenMenu={() => notify('Меню')} /></ScreenTopBarEnvironment.Provider><ScreenTopBar title="Редактировать" onBack={() => notify('Назад')} trailingAction={<EditorAutosaveStatus status="saved" />} /><CatalogInnerHeader title="Ночной город" subtitle="12 тр." backLabel="Назад к плейлистам" onBack={() => notify('Назад к плейлистам')} trailingAction={<Pressable accessibilityRole="button" accessibilityLabel="Редактировать плейлист — пример" onPress={() => notify('Редактирование плейлиста')} style={ui.iconButton}><Pencil color="#111" size={21} /></Pressable>} /><CatalogInnerHeader title="Мои плейлисты" backLabel="Назад к музыке" onBack={() => notify('Назад к музыке')} trailingAction={<Pressable accessibilityRole="button" accessibilityLabel="Создать плейлист" onPress={() => notify('Новый плейлист')} style={ui.iconButton}><Plus color="#111" size={24} /></Pressable>} /></Stack>; }
function DownloadsHeaderDemo({ notify }: DemoProps) {
  const onBack = () => notify('Назад к музыке — пример');
  const onClear = () => notify('Открытие подтверждения удаления — пример');
  return <Stack>
    <Label>Есть скачанные треки</Label>
    <DownloadedMusicHeader hasDownloads onBack={onBack} onClear={onClear} />
    <Label>Удаление выполняется</Label>
    <DownloadedMusicHeader hasDownloads clearing onBack={onBack} onClear={onClear} />
    <Label>Пустой раздел</Label>
    <DownloadedMusicHeader hasDownloads={false} onBack={onBack} onClear={onClear} />
  </Stack>;
}
function TabsDemo() { const [value, setValue] = useState('mine'); const [tab, setTab] = useState<AppTab>('music'); return <Stack><CatalogTabs tabs={[{ value: 'mine', label: 'Моя музыка' }, { value: 'browse', label: 'Обзор' }]} value={value} onChange={setValue} /><ContentTabIndicator count={2} index={value === 'mine' ? 0 : 1} style={shared.tabs}>{['Публикации', 'Музыка'].map((label, i) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: (i === 0) === (value === 'mine') }} key={label} onPress={() => setValue(i === 0 ? 'mine' : 'browse')} style={shared.profileTabButton}><Label>{label}</Label></Pressable>)}</ContentTabIndicator><BottomNavigation activeTab={tab} onChangeTab={setTab} /></Stack>; }
function MenuDemo({ notify }: DemoProps) { const [admin, setAdmin] = useState(false); const action = () => notify('Демонстрация меню'); return <View style={ui.menuFrame}><SideMenu isOpen adminMode={admin} isAdmin onChangeAdminMode={setAdmin} profile={demoProfile} onClose={action} onLogout={action} onOpenEdit={action} onOpenProfile={action} onShowMyCommunities={action} onShowMyMusic={action} onShowMessages={action} onShowModeration={action} onShowSecurity={action} onShowSettings={action} onShowSubscription={action} showModeration showSubscription={false} /></View>; }
function IdentityDemo({ notify }: DemoProps) { return <Stack><Row><AvatarEditButton entityType="account" avatarUrl={null} onPress={() => notify('Пример смены фотографии')} /><AvatarEditButton entityType="community" avatarUrl={covers[1]} onPress={() => notify('Пример обложки сообщества')} /></Row><VerifiedName name="Студия звука" isVerified style={ui.heading} /><VerifiedName name="Обычный профиль" style={ui.label} /><View style={[ui.neutral, { backgroundColor: '#111' }]}><View style={ui.between}><Text style={shared.connectProfileName}>Алекс</Text><ConnectLikeIcon liked size={21} /></View><Text style={shared.connectProfileUsername}>@demo</Text><ConnectProfileInterests interests={['CINEMA', 'PHOTOGRAPHY']} musicGenres={[...genres, 'Electronic > House > Deep']} /></View></Stack>; }
function PlaylistsDemo({ notify }: DemoProps) {
  const [customCover, setCustomCover] = useState(true);
  const trackArtwork = new Map([['profile:bandcamp:demo', covers[1]]]);
  const playlists = [
    { id: 'custom', name: 'Своя обложка', artworkUrl: customCover ? covers[0] : null, tracks: ['profile:bandcamp:demo'] },
    { id: 'automatic', name: 'Обложка из трека', tracks: ['profile:bandcamp:demo'] },
    { id: 'empty', name: 'Без обложки', tracks: [] },
  ].map(playlist => ({ id: playlist.id, name: playlist.name, artworkUrl: resolvePlaylistArtwork(playlist, trackArtwork) }));
  return <Stack>
    <View style={musicCategoryStyles.row}>
      <View style={musicCategoryStyles.slot}><MusicCategoryTile artworkUrl={playlistCategoryArtwork(playlists)} label="Мои плейлисты" onPress={() => notify('Плейлисты показаны ниже')} /></View>
      <View style={musicCategoryStyles.slot}><MusicCategoryTile artworkUrl={null} label="Отложенные релизы" onPress={() => notify('Отложенные релизы — пример')} /></View>
      <View style={musicCategoryStyles.slot}><MusicCategoryTile artworkUrl={null} label="Мои радиостанции" onPress={() => notify('Радиостанции — пример')} /></View>
    </View>
    <PlaylistGrid playlists={playlists} onOpen={() => notify('Открытие плейлиста — пример')} />
    <Action secondary onPress={() => setCustomCover(!customCover)}>{customCover ? 'Убрать свою обложку — пример' : 'Вернуть свою обложку — пример'}</Action>
  </Stack>;
}
function CatalogDemo({ notify }: DemoProps) { return <Row><CatalogCategoryTile accessibilityLabel="Музыкальные события — пример" category="Музыка" countLabel="24 события" coverUrl={covers[0]} onPress={() => notify('Категория Музыка')} /><CatalogCategoryTile accessibilityLabel="Кино — пример" category="Кино" countLabel="12 событий" onPress={() => notify('Категория Кино')} /></Row>; }
function ReleaseDemo() { return <Stack><Row><AppImage source={{ uri: covers[0] }} style={ui.releaseCover} /><View style={{ flex: 1, minWidth: 0 }}><Text style={shared.bandcampReleaseTitle}>Evening Sessions EP</Text><ReleaseMetadataRows artist="Example Artist" trackCount={4} provider="Bandcamp" releaseDateLabel="15 сентября 2026 г." genres={genres} /></View></Row><ExternalReleaseEditorField value="https://example.bandcamp.com/album/evening-sessions" onChangeText={noop} onResolve={noop} isResolving={false} hint="Релиз найден" preview={{ provider: 'bandcamp', metadata: { title: 'Evening Sessions EP', artist: 'Example Artist', artworkUrl: covers[0], tracks: [{ title: 'Night Walk' }, { title: 'Morning Light' }] } }} /><PrimaryTrackPreviewCard artist="Example Artist" artworkUrl={covers[0]} title="Night Walk" unavailableLabel="Трек недоступен" /></Stack>; }
function ChatDemo() {
  const incoming: MessagingMessage = { id: 'example-1', threadId: 'ui-kit-thread', securityMode: 'e2ee', senderAccountId: 'peer', text: 'Пойдём на концерт в субботу?', createdAt: '2026-09-15T14:00:00Z', reactions: [] };
  const outgoing = { ...incoming, id: 'example-2', senderAccountId: 'me', text: 'Да! Встретимся у входа.', createdAt: '2026-09-15T14:01:00Z', reactions: [{ emoji: '❤️', accountId: 'peer' }] };
  const callbacks = { onLongPress: noop, onOpenEvent: noop, onOpenProfile: noop, onOpenPublicPage: noop, onReact: noop };
  return <Stack><Row><ChatAvatar partner={{ name: 'Алекс', avatarUrl: null }} online /><View><Label>Алекс</Label><Text style={ui.caption}>@demo · Онлайн</Text></View></Row><MessageRow {...callbacks} accountId="me" message={incoming} interactive={false} /><MessageRow {...callbacks} accountId="me" message={outgoing} previous={incoming} interactive={false} /><MessageRow {...callbacks} accountId="me" message={{ ...outgoing, id: 'example-3', text: 'Напишу, когда буду рядом.', reactions: [] }} previous={outgoing} interactive={false} /></Stack>;
}
function SheetsDemo({ notify }: DemoProps) { const [open, setOpen] = useState(false); return <><Action secondary onPress={() => setOpen(true)}>Открыть панель</Action><AppSheetModal title="Сохранить изменения?" subtitle="Пример обычной панели" isVisible={open} onClose={() => setOpen(false)} footer={<Action onPress={() => { setOpen(false); notify('Сохранено — демонстрация'); }}>Сохранить</Action>}><Text style={ui.body}>Контент панели прокручивается отдельно от закреплённого действия. На телефоне панель занимает всю ширину, на большом экране ограничена 600 px.</Text></AppSheetModal></>; }
function PickerDemo() { const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [selected, setSelected] = useState('Москва'); return <><Action secondary onPress={() => setOpen(true)}>{selected}</Action><SelectionPickerModal title="Выберите город" isVisible={open} onClose={() => setOpen(false)} search={search} onChangeSearch={setSearch} searchPlaceholder="Поиск города" options={['Москва', 'Санкт-Петербург', 'Казань'].filter(x => x.toLowerCase().includes(search.toLowerCase())).map(title => ({ key: title, title, selected: selected === title, onPress: () => { setSelected(title); setOpen(false); } }))} /></>; }
function CalendarDemo() { const [value, setValue] = useState('15.09.2026'); return <CalendarPickerModal embedded isVisible title="Дата события" selectedValue={value} minDate={new Date(1970, 0, 1)} onClose={noop} onSelect={setValue} />; }
function DeletionDemo({ notify }: DemoProps) { const [open, setOpen] = useState(false); return <><Action secondary onPress={() => setOpen(true)}>Выбор удаления сообщения</Action><DeletionSheet isVisible={open} message busy={false} error={null} onClose={() => setOpen(false)} onDelete={scope => { setOpen(false); notify(scope === 'self' ? 'Пример: удалить у меня' : 'Пример: удалить у всех'); }} /></>; }
function FeedbackDemo({ notify }: DemoProps) { return <Stack><Row><LoadingIndicator /><LoadingIndicator size="large" /><LoadingIndicator tone="danger" /></Row><Row>{(['saved', 'saving', 'pending', 'error'] as const).map(status => <EditorAutosaveStatus key={status} status={status} />)}</Row><Action secondary onPress={() => notify('Изменения сохранены')}>Показать уведомление</Action><Action secondary onPress={() => notify('Не удалось сохранить. Попробуйте ещё раз.', 'error')}>Показать ошибку</Action></Stack>; }
function EmptyDemo({ notify }: DemoProps) { return <View style={ui.empty}><MessageSquare color="#8e99a4" size={30} /><Text style={shared.connectDisabledTitle}>Пока ничего нет</Text><Text style={shared.connectDisabledText}>Здесь появятся добавленные вами материалы.</Text><Action secondary onPress={() => notify('Повторная загрузка — пример')}>Повторить</Action></View>; }
function MotionDemo() { const [visible, setVisible] = useState(false); const reduced = useReducedMotion(); return <Stack><Action secondary onPress={() => setVisible(!visible)}>{visible ? 'Свернуть' : 'Показать подробности'}</Action><MotionDisclosure visible={visible}><View style={ui.neutral}><Text style={ui.body}>Короткое раскрытие без перемещения всей страницы. При системном уменьшении движения анимация отключается.</Text></View></MotionDisclosure><Text style={ui.caption}>Уменьшение движения: {reduced ? 'включено' : 'выключено'}</Text></Stack>; }

const baseSpecimens: Specimen[] = [
  { id: 'palette', category: 'Основа', title: 'Цвета', description: 'Нейтральная палитра и смысловые состояния.', source: 'styles.ts · sheet-design · loading-tokens', render: () => <FoundationDemo /> },
  { id: 'type', category: 'Основа', title: 'Типографика', description: 'Заголовки, основной текст, подписи и ошибки.', source: 'styles.ts', render: () => <TypographyDemo /> },
  { id: 'geometry', category: 'Основа', title: 'Размеры и интервалы', description: 'Скругления, отступы и области нажатия.', source: 'styles.ts · sheet-design', render: () => <GeometryDemo /> },
  { id: 'icons', category: 'Основа', title: 'Иконки', description: 'Lucide · 23 px · единая толщина линий.', source: 'lucide-react-native', render: () => <IconsDemo /> },
  { id: 'buttons', category: 'Управление', title: 'Кнопки и состояния', description: 'Основная, вторичная, недоступная, загрузка и удаление.', source: 'primaryAuthButton · LoadingIndicator', render: props => <ButtonsDemo {...props} /> },
  { id: 'segments', category: 'Управление', title: 'Сегменты', description: 'Два и три взаимоисключающих варианта.', source: 'AnimatedSegmentedControl', render: () => <SegmentsDemo /> },
  { id: 'switches', category: 'Управление', title: 'Переключатели и флажки', description: 'Активное, выключенное и недоступное состояние.', source: 'VolnaSwitch · authRulesCheckbox', render: () => <SwitchDemo /> },
  { id: 'goals', category: 'Управление', title: 'Множественный выбор', description: 'Цели Коннекта и выбранные чипы.', source: 'connectGoalChips', render: () => <GoalsDemo /> },
  { id: 'search', category: 'Поля', title: 'Поиск на странице', description: 'Серая капсула с очисткой введённого текста.', source: 'SearchField', render: () => <SearchDemo /> },
  { id: 'attached-search', category: 'Поля', title: 'Поиск с подсказкой', description: '50 px, радиус 25 px. Фон подсказки доходит до центра поля.', source: 'primaryTrackSearchInputRow · primaryTrackInputHint', render: () => <AttachedSearchDemo /> },
  { id: 'links', category: 'Поля', title: 'Ссылка с действием', description: 'Полностью скруглённое поле и прикреплённая подсказка.', source: 'ExternalReleaseEditorField', render: props => <LinkDemo {...props} /> },
  { id: 'form', category: 'Поля', title: 'Редактирование текста', description: 'Однострочное поле, многострочный текст и счётчик.', source: 'input · editAboutField · editAboutInput', render: () => <FormDemo /> },
  { id: 'password', category: 'Поля', title: 'Надёжность пароля', description: 'Три уровня с общей анимацией индикатора.', source: 'PasswordStrengthIndicator', render: () => <PasswordDemo /> },
  { id: 'interests', category: 'Выбор', title: 'Интересы и музыка', description: 'Общий поиск, категории, поджанры и удаление выбранного.', source: 'ConnectInterestSelector · useMusicGenrePicker', render: () => <InterestsDemo /> },
  { id: 'genres', category: 'Выбор', title: 'Фильтр жанров', description: 'Кнопка фильтра, иерархия и счётчик выбранного.', source: 'MusicGenreSelector', render: () => <GenreDemo /> },
  { id: 'range', category: 'Выбор', title: 'Диапазон возраста', description: 'Два ползунка: мышь, касание и клавиатура.', source: 'ConnectAgeRangeSlider', render: () => <RangeDemo /> },
  { id: 'picker', category: 'Выбор', title: 'Поиск и выбор значения', description: 'Общая панель выбора с поиском и отметкой.', source: 'SelectionPickerModal', render: () => <PickerDemo /> },
  { id: 'calendar', category: 'Выбор', title: 'Календарь', description: 'Переключение между днём, месяцем и годом.', source: 'CalendarPickerModal', render: () => <CalendarDemo /> },
  { id: 'headers', category: 'Навигация', title: 'Шапки экранов', description: 'Счётчики, возврат, автосохранение, вложенный каталог и число треков под названием плейлиста.', source: 'ScreenTopBar · CatalogInnerHeader', render: props => <HeadersDemo {...props} /> },
  { id: 'catalog-back', category: 'Навигация', title: 'Свайп назад из категории', description: 'Откройте плейлист и проведите вправо: возврат на один уровень, как по стрелке. Вертикальная прокрутка и нажатия сохраняются. На корневом уровне свайп выключен; экран не сдвигается.', source: 'CatalogBackArea · DrawerDismissArea · CatalogInnerHeader · PlaylistGrid', render: () => <CatalogBackDemo /> },
  { id: 'downloads-header', category: 'Музыка', title: 'Шапка скачанного', description: 'Массовое удаление — корзина справа от названия. Недоступна при удалении, скрыта в пустом разделе. Нижней ссылки и разделителя под треками нет.', source: 'DownloadedMusicHeader · CatalogInnerHeader', render: props => <DownloadsHeaderDemo {...props} /> },
  { id: 'tabs', category: 'Навигация', title: 'Вкладки', description: 'Каталог, профиль и основная нижняя навигация.', source: 'CatalogTabs · ContentTabIndicator · BottomNavigation', render: () => <TabsDemo /> },
  { id: 'menu', category: 'Навигация', title: 'Боковое меню', description: 'Профиль, разделы приложения и административный режим.', source: 'SideMenu', render: props => <MenuDemo {...props} /> },
  { id: 'identity', category: 'Карточки', title: 'Аватары, имя и интересы', description: 'Фото и имя профиля. В Коннекте каждый жанр виден отдельной плашкой под интересами.', source: 'AvatarEditButton · VerifiedName · ConnectProfileInterests · ConnectLikeIcon', render: props => <IdentityDemo {...props} /> },
  { id: 'photos', category: 'Карточки', title: 'Фотографии Коннекта', description: 'Пять слотов, удаление и изменение порядка фотографий.', source: 'ConnectPhotosEditor', render: props => <PhotosDemo {...props} /> },
  { id: 'playlists', category: 'Карточки', title: 'Плейлисты', description: 'Категории музыки и сетка плейлистов: своя обложка, обложка из трека или заглушка. Создание доступно в шапке раздела плейлистов.', source: 'MusicCategoryTile · PlaylistGrid · PlaylistArtwork · resolvePlaylistArtwork', render: props => <PlaylistsDemo {...props} /> },
  { id: 'catalog', category: 'Карточки', title: 'Категории каталога', description: 'Категория с обложкой и нейтральная заглушка.', source: 'CatalogCategoryTile', render: props => <CatalogDemo {...props} /> },
  { id: 'release', category: 'Карточки', title: 'Музыкальный релиз', description: 'Обложка, метаданные, жанры и раскрытый список треков.', source: 'AppImage · ReleaseMetadataRows · ExternalReleaseEditorField · PrimaryTrackPreviewCard', render: () => <ReleaseDemo /> },
  { id: 'chat', category: 'Сообщения', title: 'Переписка и статусы', description: 'Расшифрованные на устройстве сообщения, реакции и онлайн. Квитанции E2EE пока не показаны.', source: 'MessageRow · Avatar · Timestamp', render: () => <ChatDemo /> },
  { id: 'chat-encryption-unavailable', category: 'Сообщения', title: 'Защищённые чаты недоступны', description: 'Состояние списка при недоступности шифрования. Перехода к обычным чатам нет.', source: 'MessagesEmptyState', render: props => <MessagesEmptyState error="Защищённые чаты пока недоступны. Попробуйте позже." onRetry={() => props.notify('Повторная попытка — пример')} /> },
  { id: 'chat-store-ownership', category: 'Сообщения', title: 'Сообщения в другой вкладке', description: 'Доступ к хранилищу: занято, сессия завершена и браузер не предоставил доступ. Только вымышленные ошибки, без блокировок и ключей.', source: 'MessagesEmptyState · messagingSurfaceErrorMessage', render: props => <View>{['matrix_store_busy', 'matrix_store_retired', 'matrix_store_unavailable'].map(code => <MessagesEmptyState key={code} error={messagingSurfaceErrorMessage({ code })} onRetry={() => props.notify('Повторная попытка — пример')} />)}</View> },
  { id: 'delete', category: 'Сообщения', title: 'Удаление сообщений', description: 'Общая панель выбора «у меня» или «у всех».', source: 'DeletionSheet', render: props => <DeletionDemo {...props} /> },
  { id: 'sheet', category: 'Состояния', title: 'Нижняя панель', description: 'Заголовок, текст и закреплённое основное действие.', source: 'AppSheetModal', render: props => <SheetsDemo {...props} /> },
  { id: 'feedback', category: 'Состояния', title: 'Загрузка и уведомления', description: 'Индикаторы, автосохранение, успешный результат и ошибка.', source: 'LoadingIndicator · EditorAutosaveStatus · TopToast', render: props => <FeedbackDemo {...props} /> },
  { id: 'empty', category: 'Состояния', title: 'Пустое состояние', description: 'Объяснение и понятное следующее действие.', source: 'connectDisabledTitle · connectDisabledText', render: props => <EmptyDemo {...props} /> },
  { id: 'motion', category: 'Состояния', title: 'Раскрытие и движение', description: 'Прерываемая анимация с поддержкой reduced motion.', source: 'MotionDisclosure', render: () => <MotionDemo /> },
];

const specimens = [...baseSpecimens, ...productSpecimens];

export default function UiKitScreen() {
  const { width } = useWindowDimensions();
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Все');
  const [page, setPage] = useState(0);
  const [showCoverage, setShowCoverage] = useState(false);
  const [exactId, setExactId] = useState<string | null>(null);
  const [categoryPicker, setCategoryPicker] = useState(false);
  const [toast, setToast] = useState<ToastMessage | null>(null);
  const toastId = useRef(0);
  const scroll = useRef<ScrollView>(null);
  const categories = ['Все', ...new Set(specimens.map(item => item.category))];
  const visible = useMemo(() => specimens.filter(item => (category === 'Все' || item.category === category) && (exactId ? item.id === exactId : `${item.id} ${item.title} ${item.description} ${item.source} ${item.category}`.toLocaleLowerCase('ru').includes(query.trim().toLocaleLowerCase('ru')))), [query, category, exactId]);
  const notify: DemoProps['notify'] = (message, type = 'success') => setToast({ id: ++toastId.current, message, type });
  const compact = width < 760;
  const pageSize = 12;
  const pageCount = Math.max(1, Math.ceil(visible.length / pageSize));
  const currentPage = Math.min(page, pageCount - 1);
  const changeCategory = (value: string) => { setCategory(value); setExactId(null); setPage(0); };
  const changeQuery = (value: string) => { setQuery(value); setExactId(null); setPage(0); };
  const changePage = (value: number) => { setPage(value); scroll.current?.scrollTo({ y: 0, animated: false }); };
  return <SafeAreaView edges={['top', 'bottom']} style={ui.page}>
    <Head><title>UI Kit — VOLNA</title><meta name="description" content="Визуальная библиотека компонентов интерфейса VOLNA." /></Head>
    <View style={ui.header}><View style={ui.headerInner}><View style={ui.brand}><AppImage source={require('../../assets/volna-logo.webp')} resizeMode="contain" style={ui.logo} /><Text style={ui.brandLabel}>UI KIT</Text></View><Link href="/admpanel" asChild><Pressable accessibilityRole="link" style={ui.backLink}><ArrowLeft color="#111" size={17} /><Text style={ui.label}>В админку</Text></Pressable></Link></View></View>
    <ScrollView ref={scroll} contentContainerStyle={[ui.content, compact && ui.contentCompact]} keyboardShouldPersistTaps="handled">
      <View style={ui.hero}><Text style={ui.eyebrow}>ИНТЕРФЕЙС VOLNA</Text><Text accessibilityRole="header" style={[ui.title, compact && ui.titleCompact]}>Библиотека интерфейса</Text><Text style={ui.intro}>Визуальная библиотека интерфейса: элементы, состояния и взаимодействия. Попробуйте кнопки, поля и панели — примеры не меняют данные приложения.</Text><Text style={ui.caption}>{specimens.length} групп примеров · покрытие экранов и состояний пока частичное</Text></View>
      <View style={{ gap: 16, marginBottom: 24 }}><Action secondary onPress={() => setShowCoverage(!showCoverage)}>{showCoverage ? 'Скрыть карту интерфейса' : 'Карта покрытия и недостающие примеры'}</Action>{showCoverage ? coverage.map(area => <View key={area.title} style={ui.neutral}><Text style={ui.heading}>{area.title}</Text><Text selectable style={ui.caption}>{area.sources.join(' · ')}</Text>{area.note ? <Text style={ui.body}>{area.note}</Text> : null}{area.notShown.length ? <View style={{ gap: 4, marginTop: 12 }}><Text style={ui.label}>Пока не показано</Text>{area.notShown.map(gap => <Text key={gap} style={ui.body}>• {gap}</Text>)}</View> : null}<View style={[ui.row, { marginTop: 12 }]}>{area.examples.map(id => <Pressable accessibilityRole="button" key={id} style={ui.filter} onPress={() => { changeCategory('Все'); changeQuery(id); setExactId(id); setShowCoverage(false); }}><Text style={ui.label}>{specimens.find(item => item.id === id)?.title ?? id} →</Text></Pressable>)}</View></View>) : null}</View>
      <View style={ui.browser}><SearchField style={{ backgroundColor: '#fff' }} placeholder="Найти компонент или состояние" value={query} onChangeText={changeQuery} onClear={() => changeQuery('')} />{compact ? <Action secondary onPress={() => setCategoryPicker(true)}>Раздел: {category}</Action> : <View style={[ui.filters, { flexDirection: 'row', flexWrap: 'wrap' }]}>{categories.map(item => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: category === item }} onPress={() => changeCategory(item)} style={[ui.filter, category === item && ui.filterActive]}><Text style={[ui.filterText, category === item && ui.filterTextActive]}>{item}</Text></Pressable>)}</View>}<Text accessibilityLiveRegion="polite" style={ui.caption}>{visible.length} из {specimens.length} групп</Text></View>
      <View style={ui.grid}>{visible.slice(currentPage * pageSize, (currentPage + 1) * pageSize).map(item => <View key={item.id} testID={`ui-kit-${item.id}`} style={[ui.specimen, { width: compact ? '100%' : '48.8%' }]}><View style={ui.specimenHeader}><Text style={ui.eyebrow}>{item.category}</Text><Text accessibilityRole="header" style={ui.specimenTitle}>{item.title}</Text><Text style={ui.body}>{item.description}</Text><Text style={ui.caption}>{specimenKindLabels[fidelity[item.id as keyof typeof fidelity] as keyof typeof specimenKindLabels]}</Text></View><View style={ui.preview}>{item.render({ notify })}</View><Text selectable style={ui.source}>{item.source}</Text></View>)}</View>
      {pageCount > 1 ? <View style={[ui.row, { justifyContent: 'center', marginTop: 24 }]}><Action secondary disabled={currentPage === 0} onPress={() => changePage(currentPage - 1)}>← Назад</Action><Text style={ui.label}>Страница {currentPage + 1} из {pageCount}</Text><Action secondary disabled={currentPage === pageCount - 1} onPress={() => changePage(currentPage + 1)}>Далее →</Action></View> : null}
      {!visible.length ? <View style={ui.empty}><Text style={ui.heading}>Ничего не найдено</Text><Action secondary onPress={() => { changeQuery(''); changeCategory('Все'); }}>Сбросить поиск</Action></View> : null}
      <View style={ui.footer}><Text style={ui.caption}>Образцы используют компоненты и стили приложения. Полные правила — docs/design.md.</Text><Pressable accessibilityRole="button" onPress={() => scroll.current?.scrollTo({ y: 0, animated: false })}><Text style={ui.label}>К началу ↑</Text></Pressable></View>
    </ScrollView><SelectionPickerModal title="Раздел UI Kit" isVisible={categoryPicker} onClose={() => setCategoryPicker(false)} options={categories.map(value => ({ key: value, title: value, selected: category === value, onPress: () => { changeCategory(value); setCategoryPicker(false); } }))} /><TopToast toast={toast} onClose={id => setToast(current => current?.id === id ? null : current)} />
  </SafeAreaView>;
}

// These styles arrange the documentation page only. Specimens above reuse the
// application components/tokens instead of reproducing their visual rules here.
const ui = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#f3f5f7' }, header: { backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#d7dee5' }, headerInner: { width: '100%', maxWidth: 1280, alignSelf: 'center', paddingHorizontal: 24, height: 72, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, brand: { flexDirection: 'row', alignItems: 'center', gap: 18 }, logo: { width: 96, height: 25 }, brandLabel: { color: '#6f7b86', fontSize: 12, letterSpacing: 2, fontWeight: '600' }, backLink: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 44 },
  content: { alignSelf: 'center', width: '100%', maxWidth: 1280, padding: 24, paddingBottom: 48 }, contentCompact: { padding: 16 }, hero: { paddingTop: 28, paddingBottom: 32, gap: 14 }, eyebrow: { color: '#6f7b86', fontSize: 11, letterSpacing: 1.3, fontWeight: '600' }, title: { fontSize: 44, lineHeight: 52, fontWeight: '600', color: '#111', letterSpacing: -1.4 }, titleCompact: { fontSize: 32, lineHeight: 38 }, intro: { maxWidth: 700, fontSize: 16, lineHeight: 24, color: '#53606c' }, browser: { gap: 12, marginBottom: 24 }, filters: { gap: 8, paddingVertical: 2 }, filter: { minHeight: 40, borderRadius: 20, paddingHorizontal: 16, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: '#111' }, filterText: { fontSize: 14, color: '#53606c' }, filterTextActive: { color: '#fff' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'flex-start', rowGap: 20 }, specimen: { borderRadius: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e7ec', overflow: 'hidden' }, specimenHeader: { padding: 20, gap: 8 }, specimenTitle: { color: '#111', fontSize: 20, lineHeight: 26, fontWeight: '600' }, preview: { padding: 16, paddingTop: 8, minHeight: 100 }, source: { padding: 16, fontSize: 11, lineHeight: 17, color: '#6f7b86', borderTopWidth: 1, borderTopColor: '#f3f5f7' }, stack: { gap: 16 }, row: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 12 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 }, label: { fontSize: 14, lineHeight: 20, color: '#111', fontWeight: '500' }, body: { fontSize: 14, lineHeight: 21, color: '#6f7b86' }, caption: { fontSize: 12, lineHeight: 18, color: '#6f7b86' }, counter: { fontSize: 12, color: '#6f7b86', textAlign: 'right' }, heading: { color: '#111', fontSize: 22, lineHeight: 28, fontWeight: '600' },
  swatches: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, swatch: { width: '30%', minWidth: 74, gap: 4 }, swatchPaint: { height: 54, borderRadius: 8, borderWidth: 1, borderColor: '#e2e7ec', marginBottom: 3 }, geometry: { width: 60, height: 50, borderWidth: 1, borderColor: '#d7dee5', alignItems: 'center', justifyContent: 'center' }, spacingItem: { alignItems: 'center', gap: 4, minWidth: 24 }, iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, iconCell: { width: 65, height: 54, alignItems: 'center', justifyContent: 'center', gap: 7 }, iconName: { fontSize: 9, color: '#6f7b86' }, iconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, menuFrame: { height: 700, overflow: 'hidden', borderRadius: 8, borderWidth: 1, borderColor: '#e2e7ec' }, releaseCover: { width: 76, height: 76, borderRadius: 8 }, empty: { paddingVertical: 32, alignItems: 'center', gap: 16 }, neutral: { padding: 16, borderRadius: 8, backgroundColor: '#f3f5f7' }, footer: { paddingTop: 36, gap: 16, alignItems: 'center' },
});
