const publicPageTypeLabels = Object.freeze({
  BAR: 'Бар',
  CLUB: 'Клуб',
  JAZZ_CLUB: 'Джаз-клуб',
  RESTAURANT: 'Ресторан',
  PIZZERIA: 'Пиццерия',
  KEBAB: 'Кебабная',
  FAST_FOOD: 'Фастфуд',
  TATTOO: 'Тату-салон',
  BARBERSHOP: 'Барбершоп',
  BEAUTY: 'Бьюти-студия',
  VINYL: 'Рекорд-стор',
  VINTAGE_STORE: 'Винтажный магазин',
  CLOTHING: 'Одежда',
  CLOTHING_BRAND: 'Бренд одежды',
  ACCESSORIES: 'Аксессуары',
  ART_CLUSTER: 'Арт-кластер',
  MUSIC_LABEL: 'Музыкальный лейбл',
  MUSIC_BAND: 'Музыкальная группа',
  MUSIC_DUO: 'Музыкальный дуэт',
  PODCAST: 'Подкаст',
  RADIO_STATION: 'Радиостанция',
  BOOKING_AGENCY: 'Букинг-агентство',
  PROMO_GROUP: 'Промо-команда',
  CREATIVE_COLLECTIVE: 'Творческое объединение',
  MUSIC_FESTIVAL: 'Музыкальный фестиваль',
  FILM_FESTIVAL: 'Кинофестиваль',
  CINEMA: 'Кинотеатр',
  MUSEUM: 'Музей',
  WORKSHOP: 'Мастерская',
  THEATER: 'Театр',
  COFFEE_SHOP: 'Кофейня',
  CREATIVE_HUB: 'Креативный хаб',
  DESIGN_STUDIO: 'Студия дизайна',
  PRODUCTION_STUDIO: 'Продакшн-студия',
  CONCERT_VENUE: 'Концертная площадка',
  EXHIBITION_SPACE: 'Выставочное пространство',
  GALLERY: 'Галерея',
  INDEPENDENT_MEDIA: 'Независимое медиа',
});
module.exports = { publicPageTypeLabels };
